services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    container_name: eod-app
    volumes:
      - /eod/prod/logs:/logs
      - /eod/uploads:/eod/uploads
    restart: always
    ports:
      - "8020:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - BASE_URL=${BASE_URL}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - LOG_DIR=${LOG_DIR}
      - BSM_CLIENT_ID=${BSM_CLIENT_ID}
      - BSM_CLIENT_SECRET=${BSM_CLIENT_SECRET}
      - BSM_OAUTH_BASE_URL=${BSM_OAUTH_BASE_URL}
      - BSM_REDIRECT_URI=${BSM_REDIRECT_URI}
      - FILE_UPLOAD_DIR=/eod/uploads
      - FILE_UPLOAD_BASE_URL=${FILE_UPLOAD_BASE_URL}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - eod-network

  mysql:
    image: mysql:8.0
    container_name: eod-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-prod:/var/lib/mysql
    networks:
      - eod-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql-data-prod:
    external: true
    name: eod_mysql-data-prod

networks:
  eod-network:
    driver: bridge
